### PR TITLE
Fix for windows registry discovery

### PR DESCRIPTION
**Pull request by gorkem**
Fixes windows registry discovery that was going into a loop. Uses winreg to search for registry keys.

### CODE REVIEW

**Comment by jsdevel** [comment]
Looks like the build failed @gorkem.  Is that dependency only guaranteed to work on windows?

**Comment by gorkem** [comment]
It is because travis CI is using v0.11.16 and I had used ES6 constructs such as const.

**Comment by jsdevel** [comment]
Ideally all versions.  Can you use es5?

**Comment by gorkem** [comment]
removed all ES6 uses

**Comment by jsdevel** [comment]
Thanks!

**Pull request merged**
